const fs = require('fs')

const vars = `
REACT_APP_CONTACT_EMAIL_API=${process.env.REACT_APP_CONTACT_EMAIL_API}
REACT_APP_EVENTBRITE_ORG_ID=${process.env.REACT_APP_EVENTBRITE_ORG_ID}
REACT_APP_EVENTBRITE_TOKEN=${process.env.REACT_APP_EVENTBRITE_TOKEN}
REACT_APP_MEMBERSHIP_LIST_API=${process.env.REACT_APP_MEMBERSHIP_LIST_API}
REACT_APP_NEWSLETTER_SUBSCRIBTION_API=${process.env.REACT_APP_NEWSLETTER_SUBSCRIBTION_API}
REACT_APP_PAYPAL_CLIENT_PRODUCTION_TOKEN=${process.env.REACT_APP_PAYPAL_CLIENT_PRODUCTION_TOKEN}
REACT_APP_PAYPAL_CLIENT_SANDBOX_TOKEN=${process.env.REACT_APP_PAYPAL_CLIENT_SANDBOX_TOKEN}
`

fs.writeFileSync(`./.env`, vars)
