const fs = require('fs')
const path = `./.env`
const vars = `
 REACT_APP_CONTACT_EMAIL_API=${process.env.REACT_APP_CONTACT_EMAIL_API}\n
 REACT_APP_EVENTBRITE_ORG_ID=${process.env.REACT_APP_EVENTBRITE_ORG_ID}\n
 REACT_APP_EVENTBRITE_TOKEN=${process.env.REACT_APP_EVENTBRITE_TOKEN}\n
 REACT_APP_MEMBERSHIP_LIST_API=${process.env.REACT_APP_MEMBERSHIP_LIST_API}\n
 REACT_APP_NEWSLETTER_SUBSCRIBTION_API=${process.env.REACT_APP_NEWSLETTER_SUBSCRIBTION_API}\n
 REACT_APP_PAYPAL_CLIENT_PRODUCTION_TOKEN=${process.env.REACT_APP_PAYPAL_CLIENT_PRODUCTION_TOKEN}\n
 REACT_APP_PAYPAL_CLIENT_SANDBOX_TOKEN=${process.env.REACT_APP_PAYPAL_CLIENT_SANDBOX_TOKEN}
`
fs.writeFileSync(path, vars)
